add logo
Denisov96/tasks_ai_web pull request #16
Opened 2024-10-04 16:34 UTC by Denisov96

![image](https://github.com/user-attachments/assets/6dd3ecc7-17cb-4622-b177-1218608e2c99)

2024-10-04 18:39 UTC, SevaDer14 requested changes
Хорошо, но я советую использовать компонент Image вместо тега img для логотипа.

Еще рекомендую попробовать сделать сам логотип меньше по размеру и добавить больше пространства вокруг. Сейчас он выглядит слишком массивно и тесно

2024-10-04 18:39 UTC, SevaDer14 commented on components/TaskInput/styles.module.css
>  .inputContainer {
Я не уверен что вам нужен этот класс так как кнопку вы убрали. Попробуйте избавиться от него

2024-10-04 18:39 UTC, SevaDer14 commented on components/TaskInput/index.jsx
> +      <img src="/images/logo.png" alt="Logo" className={styles.image} />
В next.js есть специальный компонент Image. Лучше пользоваться им так как по капотом next сможет оптимизировать работу с изображением. Подробнее можете почитать в документации https://nextjs.org/docs/app/building-your-application/optimizing/images

2024-10-10 17:35 UTC, Denisov96 commented
![image](https://github.com/user-attachments/assets/ea6ea28b-e1bc-485d-baa9-305408dfef69)

2024-10-10 18:10 UTC, Denisov96 commented
![image](https://github.com/user-attachments/assets/443dcc09-7fb2-43f4-a0fc-6c587ceb8bd8)

2024-10-20 18:26 UTC, offcast-dev approved these changes

2024-10-20 18:29 UTC, merged