создает компонент Task
Denisov96/tasks_ai_web pull request #2
Opened 2024-08-02 16:35 UTC by Denisov96

2024-08-15 18:39 UTC, SevaDer14 requested changes
Отличная работа! Несколько вещей можно улучшить, но в целом все верно

2024-08-15 18:39 UTC, SevaDer14 commented on components/Task/styles.module.css
> +  .button {
мне не нравится название этого класса, как на счет .checkbox?

2024-08-15 18:39 UTC, SevaDer14 commented on components/Task/index.jsx
> +      <div className={`${styles.button} ${completed ? styles.completed : ''}`}>
здесь вы добавляете класс completed, но его нет в css файле. Вы можете использовать его для того чтобы изменить background-color чтобы было как в фигме, белый checkmark на зеленом фоне

2024-08-15 18:39 UTC, SevaDer14 commented on components/Task/index.jsx
> +import styles from "./styles.module.css";
отформатируйте код

2024-08-15 18:39 UTC, SevaDer14 commented on components/Task/styles.module.css
> +
отформатируйте код

2024-08-15 18:39 UTC, SevaDer14 commented on components/Task/index.jsx
> +    setCompleted(!completed);
то как вы здесь ставите новое значение completed в целом правильно и не является ошибкой. Однако в некоторых случаях это может приводить к багам. Если вы не хотите установить полностью новое состояние, а произвести операцию со старым состоянием (тут вы применяете опрацию логического отрицания на completed) то лучше это писать так:
```
setCompleted((completed) => !completed)
```
на занятии могу подробнее рассказать

2024-08-20 16:56 UTC, Denisov96 commented on components/Task/index.jsx
> +      <div className={`${styles.button} ${completed ? styles.completed : ''}`}>
Здравствуйте, добавил класс completed в основной css

2024-08-20 16:57 UTC, Denisov96 commented on components/Task/styles.module.css
> +  .button {
Название поменял

2024-08-20 18:39 UTC, Denisov96 commented on components/Task/index.jsx
> +      <div className={`${styles.button} ${completed ? styles.completed : ''}`}>
![image](https://github.com/user-attachments/assets/7b2a6f7d-e8ab-4f3e-b233-b114ceaf2db7)

2024-08-20 18:40 UTC, Denisov96 commented on components/Task/styles.module.css
> +  .button {
![image](https://github.com/user-attachments/assets/52cda2cf-9f14-4b83-9de4-144fe78c59ba)

2024-08-20 18:42 UTC, Denisov96 commented on components/Task/index.jsx
> +    setCompleted(!completed);
![image](https://github.com/user-attachments/assets/17efc7d7-6aaf-4911-81de-c911148eb4fd)

2024-08-20 18:44 UTC, Denisov96 commented on components/Task/index.jsx
> +      <div className={`${styles.button} ${completed ? styles.completed : ''}`}>
![image](https://github.com/user-attachments/assets/12f23add-3449-4ec9-8fd6-ebeeb31e21ec)

2024-08-20 18:47 UTC, SevaDer14 approved these changes
Отличная работа!

2024-08-20 18:49 UTC, merged